name = "rsvp-api"
main = "workers/src/index.ts"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "rsvp-db"
database_id = "" # Will be filled after creating the database

# CORS settings for Next.js frontend
[env.production]
vars = { ALLOWED_ORIGIN = "https://your-domain.com" }

[env.development]
vars = { ALLOWED_ORIGIN = "http://localhost:3000" }

# Worker settings
[build]
command = ""

# Routes (optional - for custom domain)
# routes = [
#   { pattern = "api.your-domain.com/*", zone_name = "your-domain.com" }
# ]

