name = "rsvp-api"
main = "workers/src/index.ts"
compatibility_date = "2024-01-01"
account_id = "30a65543f36c726f6ccd663476bed81e"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "rsvp-db"
database_id = "c9ced905-3c7d-4d44-8b72-aed06058b8b5"
migrations_dir = "workers/migrations"

# R2 Bucket for QR codes
[[r2_buckets]]
binding = "QR_BUCKET"
bucket_name = "rsvp-qr-codes"
preview_bucket_name = "rsvp-qr-codes-preview"

# Environment variables
# Note: Sensitive values (RESEND_API_KEY, ADMIN_PASSWORD, QR_SECRET) 
# should be set via:
# - Local: .dev.vars file (not committed)
# - Production: wrangler secret put command

# Non-sensitive configuration
[vars]
RESEND_FROM_EMAIL = "celebrate30@netcraft.com.mo"
RESEND_FROM_NAME = "NetCraft Gala Dinner 邀請系統"
EVENT_NAME = "天網(NetCraft)三十週年晚宴"
EVENT_DATE = "2025年12月17日（星期三）"
EVENT_VENUE = "澳門銀河國際會議中心地下宴會廳"
# R2 Worker URL (QR codes will be served through Worker)
R2_PUBLIC_URL = "https://rsvp-api.byross-tech.workers.dev"
# CORS settings for Next.js frontend
ALLOWED_ORIGIN = "https://rsvp.momini.app"
FRONTEND_URL = "https://rsvp.momini.app"

# Environment-specific overrides
[env.development]
vars = { ALLOWED_ORIGIN = "http://localhost:3000" }

# Worker settings
[build]
command = ""

# Routes (optional - for custom domain)
# routes = [
#   { pattern = "api.your-domain.com/*", zone_name = "your-domain.com" }
# ]

